"""Ensemble uncertainty band (M1.5).

Wind forecasts are uncertain, and a single deterministic plume drawn as a crisp
line implies precision the model does not have. This wrapper runs the Tier-1
engine across many wind-profile members and reports, per grid cell, the
PROBABILITY that dose rate exceeds a level. Contouring that probability at,
say, 10 / 50 / 90 percent turns one false-confident line into an honest band:
"very likely at least this far, possibly as far as that."

For now members are generated by perturbing a deterministic profile (coherent
direction + speed uncertainty, plus mild per-level shear jitter). Swapping in
true Open-Meteo ensemble members is a fetch-layer change only -- `run_ensemble`
already takes a list of member profiles.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.interpolate import RegularGridInterpolator

from . import tier1

DEFAULT_PROB_LEVELS = (0.1, 0.5, 0.9)


@dataclass
class EnsembleResult:
    x_miles: np.ndarray
    y_miles: np.ndarray
    prob_by_level: dict[float, np.ndarray]  # dose level (R/hr) -> P(exceed) field
    mean_dose_h1: np.ndarray
    n_members: int
    mean_fraction_aloft: float


def perturb_profile(
    base_u: np.ndarray,
    base_v: np.ndarray,
    n_members: int = 12,
    dir_jitter_deg: float = 12.0,
    speed_jitter_frac: float = 0.15,
    shear_jitter_frac: float = 0.08,
    seed: int | None = 42,
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Generate member wind profiles by perturbing a base profile.

    Each member gets a coherent whole-column rotation and speed scale (the
    dominant forecast uncertainty in the mean flow), plus small independent
    per-level jitter (uncertainty in the shear itself).
    """
    rng = np.random.default_rng(seed)
    base_u = np.asarray(base_u, dtype=float)
    base_v = np.asarray(base_v, dtype=float)
    members = []
    for _ in range(n_members):
        theta = np.deg2rad(rng.normal(0.0, dir_jitter_deg))
        scale = 1.0 + rng.normal(0.0, speed_jitter_frac)
        c, s = np.cos(theta), np.sin(theta)
        u = scale * (c * base_u - s * base_v)
        v = scale * (s * base_u + c * base_v)
        # per-level shear jitter
        u = u * (1.0 + rng.normal(0.0, shear_jitter_frac, size=u.shape))
        v = v * (1.0 + rng.normal(0.0, shear_jitter_frac, size=v.shape))
        members.append((u, v))
    return members


def run_ensemble(
    *,
    yield_mt: float,
    fission_fraction: float,
    heights_m: np.ndarray,
    members: list[tuple[np.ndarray, np.ndarray]],
    levels_rhr=(1.0, 10.0, 100.0, 1000.0),
    resolution_miles: float = 3.0,
    n_bins: int = 10,
    n_layers: int = 8,
    dt_s: float = 180.0,
) -> EnsembleResult:
    """Run all members and compute per-cell exceedance probability per level."""
    runs = []
    aloft = []
    for (u, v) in members:
        r = tier1.simulate(
            yield_mt=yield_mt, fission_fraction=fission_fraction,
            heights_m=heights_m, wind_u_ms=u, wind_v_ms=v,
            n_bins=n_bins, n_layers=n_layers, dt_s=dt_s,
            resolution_miles=resolution_miles,
        )
        runs.append(r)
        aloft.append(r.fraction_aloft)

    # common grid = union of member extents at fixed resolution
    x_min = min(r.x_miles[0] for r in runs)
    x_max = max(r.x_miles[-1] for r in runs)
    y_min = min(r.y_miles[0] for r in runs)
    y_max = max(r.y_miles[-1] for r in runs)
    nx = min(int((x_max - x_min) / resolution_miles) + 1, 700)
    ny = min(int((y_max - y_min) / resolution_miles) + 1, 700)
    cx = np.linspace(x_min, x_max, nx)
    cy = np.linspace(y_min, y_max, ny)
    CX, CY = np.meshgrid(cx, cy)
    pts = np.column_stack([CY.ravel(), CX.ravel()])

    stack = np.empty((len(runs), ny, nx))
    for i, r in enumerate(runs):
        interp = RegularGridInterpolator(
            (r.y_miles, r.x_miles), r.dose_rate_h1,
            bounds_error=False, fill_value=0.0,
        )
        stack[i] = interp(pts).reshape(ny, nx)

    prob_by_level = {
        lvl: (stack >= lvl).mean(axis=0) for lvl in levels_rhr
    }
    mean_dose = stack.mean(axis=0)

    return EnsembleResult(
        x_miles=cx, y_miles=cy,
        prob_by_level=prob_by_level,
        mean_dose_h1=mean_dose,
        n_members=len(runs),
        mean_fraction_aloft=float(np.mean(aloft)),
    )
